---
all:
  children:
    homelab:
      children:
        servers:
          hosts:
            homelab-server-01:
              ansible_host: 192.168.1.100
              ansible_user: homelab
              ansible_python_interpreter: /usr/bin/python3
            # homelab-server-02:
            #   ansible_host: 192.168.1.101
            #   ansible_user: homelab

        agents:
          hosts:
            homelab-agent-01:
              ansible_host: 192.168.1.110
              ansible_user: homelab
              ansible_python_interpreter: /usr/bin/python3
            # homelab-agent-02:
            #   ansible_host: 192.168.1.111
            #   ansible_user: homelab

  vars:
    # Common variables for all hosts
    timezone: America/New_York
    ntp_servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
